[changelog]
header = """
# Changelog\n
"""
body = """
{% if version %}\
  ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
  ## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for group, commits in commits | group_by(attribute="scope") %}
      #### {{ group | upper_first }}
      {% for commit in commits %}
        - {{ commit.message | upper_first }}\
      {% endfor %}
    {% endfor %}\
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^style", group = "Styling" },
  { message = "^test", group = "Testing" },
  { message = "^build", group = "Build" },
  { message = "^docs: update Changelog", skip = true },
  { message = "^docs", group = "Documentation", default_scope = "unscoped" },
  { message = "^ci", group = "Continuous Integration" },
  { message = "^cd", group = "Continuous Delivery" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore", group = "Miscellaneous Tasks" },
  { body = ".*security", group = "Security" },
]
filter_commits = false
topo_order = false
sort_commits = "oldest"
